name: Server Health Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      flask:
        image: python:3.9
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
        ports:
          - 5000:5000
        volumes:
          - .:/app
        working-directory: /app
        options: >-
          --health-cmd "curl -f http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests

    - name: Start Flask server
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 5  # Даем серверу время на запуск

    - name: Run tests
      env:
        BASE_URL: http://localhost:5000
      run: |
        pytest tests/server_healthcheck.py -v
